# Generated by Django 5.2.7 on 2025-11-18 17:38

import django.core.validators
import django.db.models.deletion
import resources.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название ресурса"),
                ),
                (
                    "location",
                    models.CharField(max_length=500, verbose_name="Местоположение"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Максимальное количество человек",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        help_text="Изображение или документ с правилами",
                        null=True,
                        upload_to=resources.models.resource_file_upload_path,
                        verbose_name="Прикрепленный файл",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные ресурсы скрыты из поиска",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
                "db_table": "resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="resources_is_acti_e9e883_idx",
                    ),
                    models.Index(
                        fields=["location"], name="resources_locatio_296946_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "path",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="Путь к файлу"
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Размер файла (байты)",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME-тип файла"),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Оригинальное имя файла"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец файла",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный файл",
                "verbose_name_plural": "Загруженные файлы",
                "db_table": "file_uploads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_user", "created_at"],
                        name="file_upload_owner_u_8250ca_idx",
                    ),
                    models.Index(
                        fields=["mime_type"], name="file_upload_mime_ty_3bcfb1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="file_upload_created_56b8c3_idx"
                    ),
                ],
            },
        ),
    ]
